### ISSUE TITLE
按照书中 npm run dev 出现报错

### ISSUE THREAD

**Issue by niusz** [sg552/vue_js_lesson_demo#1]
npm ERR! path /Users/huiwenhuang/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/huiwenhuang/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huiwenhuang/.npm/_logs/2019-02-28T05_33_57_370Z-debug.log

**Comment by niusz** [comment]
找到方法了： `npm install` 然后再 `npm run dev`就ok

**Comment by niusz** [comment]
还有一个不了解 书中的npm install -v 是个什么命令啊？网上都搜不到这个命令！

**Comment by sg552** [comment]
npm install -v 出现在多少页？ 
目前来看，这个是看npm的版本号的。 有 npm -v 就可以了。 npm install -v 中的"install"似乎是多余的。

**Comment by sg552** [comment]
npm install --verbose 
这个命令是用来显示 npm install 的详细情况的,用来做排查非常方便.
